version: '3.8'
services:
    cache:
        image: redis
        container_name: cache
        ports:
            - 6379:3001
        volumes:
            - ./storage/redis:/data
    db:
        image: mongo
        container_name: db
        ports:
            - 27017:3002
        volumes:
            - ./storage/db:/data/db
        environment:
            MONGO_INITDB_ROOT_PASSWORD: P4sswordDBTEST
    api:
        build: '.'
        container_name: api
        links:
            - cache
            - db
        depends_on: 
            - cache
            - db
        ports:
            - 3000:3000